### ISSUE TITLE
Global Entries Not Working

### ISSUE THREAD

**Issue by 60lapie60** [ZedDevStuff/USTManager#10]
The rest of my replacements work perfectly fine, but the global entries do not work. I've found the correct clip names and entered them, so what else should I add?
    "global": [
      {
        "Part": "shopmusic",
        "Path": "08. Main Menu 2 (Dark Ruins).mp3"
      },
	  {
        "Part": "shopmusic2",
        "Path": "18. Main Menu 3 (Snowdin).mp3"
      },
	  {
        "Part": "shopmusic3",
        "Path": "34. Main Menu 4 (Dunes).mp3"
      },
	  {
        "Part": "shopmusic4",
        "Path": "76. Main Menu 5 (Steamworks).mp3"
      },
	  {
	"Part": "Theme on Piano and Horns",
        "Path": "10. Justice.mp3"
      }
    ],

**Comment by ZedDevStuff** [comment]
Can you send the LogOutput.log file inside the BepInEx folder? Try loading
the UST before sending it to make sure I can see what I need

**Comment by 60lapie60** [comment]
[LogOutput.log](https://github.com/ZedDevStuff/USTManager/files/14002494/LogOutput.log)
Here it is.

**Comment by ZedDevStuff** [comment]
It seems like the Shop music uses PlayOnAwake, which i can't do anything about for now. I have some ideas that I'll have to test.

**Comment by ZedDevStuff** [comment]
The latest update (1.4.3) _should_ be able to target those.
