### ISSUE TITLE
Can't use more than 2 USTs at a time

### ISSUE THREAD

**Issue by UntotenTheo** [ZedDevStuff/USTManager#11]
**Describe the bug**
Can't use more than 2 USTs at a time

**To Reproduce**
1. Select 3 USTs
2. Try and press OK
3. Check console
4. ☹️

**Expected behavior**
I expected to be able to use more than 2 USTs at a time

**Screenshots**
![image](https://github.com/ZedDevStuff/USTManager/assets/75056493/693d7868-b983-4ec6-aa56-195a5f250a74)
![image](https://github.com/ZedDevStuff/USTManager/assets/75056493/7a2f2fc5-f8c7-421e-820d-041fd7c531ae)

**Desktop (please complete the following information):**
 - OS: Windows
 - Mod version 1.4.0

**Additional context**
[the log](https://pastebin.com/qG1QyQEy)

**Comment by ZedDevStuff** [comment]
Fixed with latest commit https://github.com/ZedDevStuff/USTManager/commit/58fa580542d4239ca558b94242993f1e6073ec2e
Thunderstore update waiting for approval.
