### ISSUE TITLE
A way to make sounds only apply to (certain) weapons?

### ISSUE THREAD

**Issue by UntotenTheo** [ZedDevStuff/USTManager#12]
**Is your feature request related to a problem? Please describe.**
So I'm currently trying to port BVSSICs Chunked Up Weapons to USTManager, but I've noticed that a lot of sounds are shared between other weapons and enemies, causing stuff to sound pretty weird in some places.

**Describe the solution you'd like**
maybe some sort of additional syntax that you can add as a sort of suffix/prefix so a certain sound replacement only applies to a specific weapon? (or maybe enemies too?)
example uhhh
`"AltRevolverShoot1D": "RevolverSounds/Alt/AltRevPrimaryFire.wav": "weapon.AltPiercer",`
that way the sound is only changed for AltPiercer, and anything else that uses `AltRevolverShoot1D` doesn't have their sound changed

**Describe alternatives you've considered**
yeah i got nothig </3

**Comment by ZedDevStuff** [comment]
This is outside the scope of USTManager but I think I can make an extension/plugin for USTManager to support it but it'll take a few days, worst case 1 or 2 weeks if I don't have the time to get something together. Anyway I just need to restructure some small things in USTManager first but that should be fast

**Comment by UntotenTheo** [comment]
Take your time chief, I can wait

Thanks for taking this into consideration though you the goat 🐟
