### ISSUE TITLE
Weapon Sound Bug when using Levels section

### ISSUE THREAD

**Issue by UntotenTheo** [ZedDevStuff/USTManager#15]
**Describe the bug**
Using the Levels section for the .ust file causes weapon sounds to seemingly break, using the Global section to replace music instead causes no such issues.

**To Reproduce**
1.  Load up this weapon sound pack
[BVSSICsChunkedUpWeaponsReborn.zip](https://github.com/ZedDevStuff/USTManager/files/14078948/BVSSICsChunkedUpWeaponsReborn.zip)
2. Test it, it should work (Note: Only changes slab revolvers and shotguns atm)
3. Load up this music pack [7-2 Ultra Combat](https://discord.com/channels/602067255454466069/887829304535285760/1196269917880713306)
(too big for github direct upload so discord link it is)
4. Test weapon sounds, they should be gone
5. (sorry for this) change `levels` to `global`, `clean2` to `7-2 Clean` and `battle2` to `7-2` in the Ultra Combat `.ust` file
6. Load the pack again
7. Weapon sounds should work
(Note: you dont need to go into 7-2 for this, just load the pack)

**Expected behavior**
i expected weapon sounds to still work yeah

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Mod version 1.4.2

**Additional context**
nothing in the logs it seems

**Comment by UntotenTheo** [comment]
Update: it seems to be caused by any loaded pack not having a `"global"` section still in the .ust file

removing a `global` section causes weapon sounds (and presumably, anything else in the global section) to break entirely

**Comment by UntotenTheo** [comment]
Update 2: so i was trying out a diff pack, i added a global section to it (from the template) and that pack broke but weapon sounds didnt

i genuinely dont know what to make of this

**Comment by ZedDevStuff** [comment]
I'll take a look as soon as i have a bit of free time (either in 3 hours or 6)

**Comment by ZedDevStuff** [comment]
Should be fixed by 1.4.3
