### ISSUE TITLE
Crashes when having a UST loaded

### ISSUE THREAD

**Issue by winterviola** [ZedDevStuff/USTManager#16]
**Describe the bug**
Sometimes having a UST loaded causes strange crashes at different points. When using just USTManager, it often will crash when trying to exit a level from the pause menu (though not consistently). The bug gets worse if AngryLevelLoader is installed, where it will crash when just trying to load a level (including both regular and angry levels).

**To Reproduce**
Steps to reproduce the behavior (just USTManager):
1. Load a level that has a UST replacement (in my case it was 0-2).
2. Load the UST from the pause menu.
3. Exit and re-enter the level, repeat until crash happens.

**Expected behavior**
The game shouldn't be crashing. The same `.ust` file used worked as intended in the previous version.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Mod version: 1.4.3

**Comment by ZedDevStuff** [comment]
Can you please give me the logs?

**Comment by ZedDevStuff** [comment]
Nothing seems wrong? It just... stopped working randomly? Can you try doing the same thing and see if it happens again? It could just be BepInEx or something else. It does happen to me randomly with any mod when I'm testing, typically when i first add a mod

**Comment by winterviola** [comment]
I had it happen multiple times while the console was open and it never printed anything useful before or after the crash handler appears. I saw someone in NBDS say they had a similar crash while using it so I don't think it's a problem on my side.

**Comment by Abel-sketch** [comment]
I have been having the same error, in fact, while playing 6-1 with a UST loaded it crash in the final room

**Comment by ZedDevStuff** [comment]
Could it be my Awake patch doing that somehow? I'll have to check tomorrow

**Comment by winterviola** [comment]
Something is probably up with the patch considering using other mods alongside it seem to always make the issue worse, even if they don't mess with sound at all (like EasyPZ causing consistent crashes on level loads).

**Comment by ZedDevStuff** [comment]
I'm really wondering how this happens. I'll try something

Le mar. 6 févr. 2024, 11:54, winterviola ***@***.***> a
écrit :

**Comment by ZedDevStuff** [comment]
Should be fixed by 1.5.0
