### ISSUE TITLE
GKLJNDSXCLFHXZCOGNISJHB

### ISSUE THREAD

**Issue by N0VA-The-Git-User** [ZedDevStuff/USTManager#17]
**Describe the bug**
when changing the p-2 battle theme it doesn't work

**To Reproduce**
1. create a ust 
![image](https://github.com/ZedDevStuff/USTManager/assets/145279552/7a461562-2728-40c9-9a1a-0b9a1a959c15)

2. apply ust
3. go to p-2
4. when non calm battle theme starts, calm theme replays.

**Expected behavior**
for tenebre soulja sangue to play

**Screenshots**
up there

**Desktop (please complete the following information):**
 - OS:windows
 - Mod version 1.4.3

**Comment by N0VA-The-Git-User** [comment]
?

**Comment by ZedDevStuff** [comment]
That's probably a MusicChanger thing, I'll take a look and push an update in a few hours if I have the time

**Comment by riley-9054** [comment]
the problem appears to be a comma at the end of "Tenebre-Soulja-Sangue.mp3"
you shouldn't have a comma there if it's the last thing to be modified in that level.
