### ISSUE TITLE
UST file doesn't show up in game

### ISSUE THREAD

**Issue by Clanks00M** [ZedDevStuff/USTManager#19]
**Describe the bug**
I created a UST file, but it won't show up in game. I've triple-checked everything I could think of that could be wrong, but it just refuses to even appear in the UST menu.

**To Reproduce**
1. Create a UST file.
2. Open the game.
3. Open the UST options in game.

**Expected behavior**
The file appearing.

**Screenshots**
![Screenshot 2024-02-18 215452](https://github.com/ZedDevStuff/USTManager/assets/149522195/d1bf968c-905b-4104-8ae2-93bc607a05d8)
![Screenshot 2024-02-18 215517](https://github.com/ZedDevStuff/USTManager/assets/149522195/5e6179c5-ecad-4964-a317-a82b0306f0cf)

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Mod version: 1.4.4

**Comment by ZedDevStuff** [comment]
Send the logs

**Comment by Clanks00M** [comment]
> Send the logs

I assume you mean the BepInEx logs, so here: 
![Screenshot 2024-02-19 223915](https://github.com/ZedDevStuff/USTManager/assets/149522195/c0c93ab7-11b2-412b-b2a2-a6746af2cace)
![Screenshot 2024-02-19 223929](https://github.com/ZedDevStuff/USTManager/assets/149522195/7c9b9b3d-272b-474b-a36d-7bb3389e1cd2)
![Screenshot 2024-02-19 223941](https://github.com/ZedDevStuff/USTManager/assets/149522195/9a72d6f9-db35-450a-93f8-86fb6397fa2c)
![Screenshot 2024-02-19 223956](https://github.com/ZedDevStuff/USTManager/assets/149522195/13e5746d-50e5-46b5-80d6-6b63f3be5f13)
![Screenshot 2024-02-19 224009](https://github.com/ZedDevStuff/USTManager/assets/149522195/454008ad-2b4e-4d0b-b6a8-54fb36174034)

**Comment by ZedDevStuff** [comment]
Very late but just use https://github.com/ZedDevStuff/USTMaker or https://ustmakerweb.zeddevstuff.dev/ if you don't wanna download anything

**Comment by BlixerYoshi** [comment]
@ZedDevStuff I still have this issue, and not even USTMaker and ZIP files are helping me!!!
