### ISSUE TITLE
Crashes While USTManager is Installed

### ISSUE THREAD

**Issue by UntotenTheo** [ZedDevStuff/USTManager#20]
**Describe the bug**
The game crashes unexpectedly, USTManager is most certainly the culprit.

**To Reproduce**
1. Have USTManager installed
2. Change Levels, beat maps, exit to main menu, time until crash seems to be random

**Expected behavior**
No crashes

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Mod version: 1.4.4

**Additional context**
Unfortunately, nothing is printed in the logs that could potentially help with this, although if I were to guess its related to that OnAwake thing that was added a while back.

**Comment by ZedDevStuff** [comment]
Fixed for a while
