### ISSUE TITLE
Terminal Songs can't be changed

### ISSUE THREAD

**Issue by UntotenTheo** [ZedDevStuff/USTManager#22]
**Describe the bug**
Terminal Songs can't be changed

**To Reproduce**
1. 0-S works best but Sandbox works too, go to either location
2. Have a UST that changes the Theme on Music Box song to something else
[For your convenience, you may use this.](https://github.com/ZedDevStuff/USTManager/files/14476372/OrderMusicBoxSecretTerminal.zip)
3. Walk to a Secret/Black Terminal, theme doesn't play
4. If in 0-S, spawn an unblinded enemy, Theme on Music Box replacement plays

For other Terminals, the song doesn't play outright.

**Expected behavior**
I expected Terminals to be able to play replaced songs

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Mod version: 1.5.0

**Comment by ZedDevStuff** [comment]
Give v1.5.4 a try with the experimental option enabled https://thunderstore.io/c/ultrakill/p/ZedDev/USTManager/changelog/
Reopen this issue if it doesn't work. Sadly this is the most i can do because of Addressables and a lot of other stuff
