### ISSUE TITLE
UST shows up in-game, but does not play

### ISSUE THREAD

**Issue by kierkat10** [ZedDevStuff/USTManager#24]
I made a UST for P-2's clean track, and it does not play, yet it still shows in the menu. I checked it using a JSON validator and it passed. What is the issue?

Here is the .ust file:
![image](https://github.com/ZedDevStuff/USTManager/assets/136650292/cc2178d8-0e13-4cfb-a3fd-d0f346cf30b2)

And here's a screenshot of the folder:
![image](https://github.com/ZedDevStuff/USTManager/assets/136650292/1a139cf4-e6d1-46cb-ae36-4add4604887c)

On a lighter note, the .png also does not show in the menu and is just a white square.

**Comment by kierkat10** [comment]
Removing the "global" section also seemed to do nothing.

**Comment by kierkat10** [comment]
@ZedDevStuff?

**Comment by ZedDevStuff** [comment]
> @ZedDevStuff?

Sorry I'm pretty busy recently. Try removing the global entry and iirc the icon only works if it's named icon.png

**Comment by kierkat10** [comment]
Found the solution:
You can't have spaces in your .mp3/.wav file

That's it :D
