### ISSUE TITLE
Hotfix update that allows us to open the menu

### ISSUE THREAD

**Issue by UntotenTheo** [ZedDevStuff/USTManager#29]
**Is your feature request related to a problem? Please describe.**
We are unable to open the USTManager menu despite the mod still working well (even with limited functionality)

**Describe the solution you'd like**
A Hotfix update that at least lets us open the menu

**Describe alternatives you've considered**
uhh i can edit the lastused.json files directly but thats kinda annoying lma o

**Comment by ZedDevStuff** [comment]
Fixed by 1.5.1
