### ISSUE TITLE
unknown command ust.debug

### ISSUE THREAD

**Issue by surytrap** [ZedDevStuff/USTManager#30]
**Describe the bug**
no ust commands in f8 console

**To Reproduce**
1. open console
2. type ust.debug and enter
3. unknown command

**Expected behavior**
a command tip while typing and some proper feedback on enter

**Screenshots**
![image](https://github.com/ZedDevStuff/USTManager/assets/104792447/1d0807d7-d0ab-45b8-b1b5-7dffa5c49a96)

**Desktop (please complete the following information):**
 - OS: window
 - Mod version latest (1.5.1)

**Comment by ZedDevStuff** [comment]
Fixed in 1.5.2
