### ISSUE TITLE
Railcannon & other broken sounds

### ISSUE THREAD

**Issue by AMemeLad** [ZedDevStuff/USTManager#32]
**Da bug**
Hey, I've been trying to replace the Railcannon sounds, but it doesn't seem to work. I checked the other issues, and it seems like I'm not the only one who's had this problem too, like this one: https://github.com/ZedDevStuff/USTManager/issues/23
I'm wondering if they'll be fixed soon?

**Expected behavior**
This file does not replace the Railcannon firing sounds.

![image](https://github.com/user-attachments/assets/00962182-a179-4ea2-98ec-ef11275c7895)
![image](https://github.com/user-attachments/assets/586439ca-efb1-48e4-8292-675ced9017bd)
I double-checked everything and made sure the JSON was formatted correctly, you can see here.
(I have an extra sound file incase I need to tweak the one I made first.)

**Desktop**
 - OS: Windows 10
 - Mod version: v1.5.2

This is also my first time reporting an issue so I don't know how good this is.

**Comment by ZedDevStuff** [comment]
Give v1.5.4 a try with the experimental option enabled https://thunderstore.io/c/ultrakill/p/ZedDev/USTManager/changelog/
Reopen this issue if it doesn't work. Sadly this is the most i can do because of Addressables and a lot of other stuff

**Comment by AMemeLad** [comment]
Ok yeah the Railcannon sounds works now thank youu
But what do you mean at the cost of performance? Gameplay seems the same to me.

**Comment by ZedDevStuff** [comment]
I'm calling a specific method each frame. It's the same one that ust.debug uses to list audio sources and on top of that I'm checking for a component on each of those sources. On my machine that ate around 400μs (0.4ms) for 91 sources which wasn't a lot but I have no idea what it would be like on weaker machines
