### ISSUE TITLE
"mp_useless" and "BlackHoleLoop" global sounds don't work

### ISSUE THREAD

**Issue by riley-9054** [ZedDevStuff/USTManager#33]
I have tried replacing both those sounds and have made sure I did not make any typos. All other global sounds I've replaced (a lot of them btw) have worked, but these two haven't. They stay as their vanilla sounds no matter what.

**Comment by ZedDevStuff** [comment]
Give v1.5.4 a try with the experimental option enabled https://thunderstore.io/c/ultrakill/p/ZedDev/USTManager/changelog/
Reopen this issue if it doesn't work. Sadly this is the most i can do because of Addressables and a lot of other stuff
