### ISSUE TITLE
Centaur A-1 can't be replaced by anything (Supposedly) & Railcannon Firing Sound

### ISSUE THREAD

**Issue by UntotenTheo** [ZedDevStuff/USTManager#7]
now i know that 7-4 isnt compatible for a reason but...

also RailcannonFire4 cant be overrided for some reason figured id tell you

**Comment by UntotenTheo** [comment]
The issue applies to Centaur B-1 as well

**Comment by UntotenTheo** [comment]
also yeah i did make sure that the syntax and stuff were correct
this is a mod issue most likely

**Comment by ZedDevStuff** [comment]
I'll take a look when I'm on my computer. I think I know the problem but
might be something else considering you actually already have the clip
name. If it's the former, I'm still trying to find how to fix that. The
latter should be fixable a lot more easily

**Comment by UntotenTheo** [comment]
take your time, we can wait !

in case you need a pack that you can use for testing (or to see if i messed up the syntax with the .ust file) then i have a pack ready

https://discord.com/channels/602067255454466069/887829304535285760/1196070632027332608

(message link so you dont think im trying to send a zipbomb </3)

**Comment by ZedDevStuff** [comment]
Awesome, thanks!

**Comment by ZedDevStuff** [comment]
Closed, fixed int latest version
